[Configuration]

# "graphics" : graphical interface module
#   "pygame" with loop frame ideal for animated graphics 2D
#   "tkinter" with event loop ideal for static widget graphics 2D(GUI)
#   "pyOpenGL" with loop frame, uses OpenGL API for 3D graphics
#   "webapp" future extensions
#   "console" no graphics, only command line
graphics = pygame

# "mode" : type of execution mode
#   "play" checkers game between player 1 and player 2
#   "view" view checkers game from archive
#   "scan" like view mode but without graphics refresh
#   "data" Unsupervised Learning (UL) data extraction
mode = data

# "player1_name" : identification player 1
#   "<name_player> name player for storage data
player1_name = name1 surname1

# "player1_engine" : type of decision engine for player 1
#   Hint: valid only in 'play' mode !
#   "player" mouse or keyboard moves
#   "classic" MiniMax + Alpha-Beta Pruning
#   "SL" Supervised Learning
#   "RL" Reinforcement Learning
player1_engine = player

# "player2_name" : identification player 2
#   "<name_player> name player for storage data
player2_name = name2 surname2

# "player2_engine" : type of decision engine for player 2
#   Hint: valid only in 'play' mode !
#   "player" mouse or keyboard moves
#   "classic" MiniMax + Alpha-Beta Pruning
#   "supervised" Supervised Learning (SL)
#   "reinforcement" Reinforcement Learning (RL)
player2_engine = player

# "parity_move" : Maximum number of moves without capturing any pieces and
# without moving any mans (counted by both players)
# parity_move = 20

# "restore" : restore checkerboards state from archive /restores
#   Hint: delete option if normal game start !
#   "<name_checkerboard> checkerboard state name
# restore = state_20260429092314103268.json

# "import_name" : resource name for data import (.db/.pdn)
# import_name = CI2007.pdn

# "import_game" : identifier of the first game to import (default = 1)
#   Hint: it depends on the type of resource (order number for .pdn, order number 
#   or better pk for .db) !
# import_game = 1

# "export_name" : resource name for data export (.db/.pdn)
# export_name = ci2007.db

# "timeout_selected" : timeout selected in msec for moves steps in view mode. 
# Setting it to zero will make the timeout infinite; to continue, a keyboard (space) or 
# mouse (left-click) event is required
#   Hint: valid only in 'view' mode !
timeout_selected = 0

# "timeout_destinated" : timeout destinated in msec for moves steps in view mode. 
# Setting it to zero will make the timeout infinite; to continue, a keyboard (space) or 
# mouse (left-click) event is required
#   Hint: valid only in 'view' mode !
timeout_destinated = 2000

# "timeout_validated" : timeout validated in msec for moves steps in view mode. 
# Setting it to zero will make the timeout infinite; to continue, a keyboard (space) or 
# mouse (left-click) event is required
#   Hint: valid only in 'view' mode !
timeout_validated = 2000

# "seed" : use for randomization with testable determinism
# seed = 23

# Hint: TODO UL type option (with archive /dataset) !
#   Hint: valid only in 'data' mode !
