[Configuration]

# "graphics" : graphical interface module
#   "pygame" with loop frame ideal for animated graphics 2D
#   "tkinter" with event loop ideal for static widget graphics 2D(GUI)
#   "pyOpenGL" with loop frame, uses OpenGL API for 3D graphics
#   "webapp" future extensions
#   "console" no graphics, only command line
graphics = pygame

# "mode" : type of execution mode
#   "play" checkers game between player 1 and player 2
#   "view" view checkers game from archive
#   "data" Unsupervised Learning (UL) data extraction
mode = play

# "player1" : type of decision engine for player 1
#   N.B.: valid only in 'play' mode !
#   "manual" mouse or keyboard moves
#   "classic" MiniMax + Alpha-Beta Pruning
#   "SL" Supervised Learning
#   "RL" Reinforcement Learning
player1 = manual

# "player2" : type of decision engine for player 2
#   N.B.: valid only in 'play' mode !
#   "manual" mouse or keyboard moves
#   "classic" MiniMax + Alpha-Beta Pruning
#   "supervised" Supervised Learning (SL)
#   "reinforcement" Reinforcement Learning (RL)
player2 = manual

# "restore" : restore checkerboards state from archive /restores
#   N.B.: delete option if normal game start !
#   "<name_checkerboard> checkerboard state name

# "history_database" : activation of historical game storage on database
# 	N.B.: if omitted, storing does not occur !
#   "<name_database> database name for game to storage

# "view_database" : database name from which to view the game
#   N.B.: valid only in 'view' mode !
#   "<name_database> database name from archive /database

# "view_id" : game identifier to view
#   N.B.: valid only in 'view' mode !
#   "<id> game identifier in the chosen database

# N.B.: TODO UL type option (with archive /dataset) !
#   N.B.: valid only in 'data' mode !
