[Configuration]

# "graphics" : graphical interface module
#   "pygame" with loop frame ideal for animated graphics 2D
#   "tkinter" with event loop ideal for static widget graphics 2D(GUI)
#   "pyOpenGL" with loop frame, uses OpenGL API for 3D graphics
#   "webapp" future extensions
#   "console" no graphics, only command line
graphics = pygame

# "mode" : type of execution mode
#   "play" checkers game between player 1 and player 2
#   "view" view checkers game from archive
#   "data" Unsupervised Learning (UL) data extraction
mode = play

# "player1_name" : identification player 1
#   "<name_player> name player for storage data
player1_name = name1 surname1

# "player1_engine" : type of decision engine for player 1
#   N.B.: valid only in 'play' mode !
#   "player" mouse or keyboard moves
#   "classic" MiniMax + Alpha-Beta Pruning
#   "SL" Supervised Learning
#   "RL" Reinforcement Learning
player1_engine = player

# "player2_name" : identification player 2
#   "<name_player> name player for storage data
player2_name = name2 surname2

# "player2_engine" : type of decision engine for player 2
#   N.B.: valid only in 'play' mode !
#   "player" mouse or keyboard moves
#   "classic" MiniMax + Alpha-Beta Pruning
#   "supervised" Supervised Learning (SL)
#   "reinforcement" Reinforcement Learning (RL)
player2_engine = player

# "parity_move" : massimo numero di mosse senza che venga catturato alcun pezzo e 
# senza che nessuna pedina si sia mossa (conteggio su entrambi i giocatori)
parity_move = 20

# "restore" : restore checkerboards state from archive /restores
#   N.B.: delete option if normal game start !
#   "<name_checkerboard> checkerboard state name
#restore = restores/state_reset.json
#restore = restores/state_test01.json
restore = restores/state_test02.json

# "history_database" : activation of historical game storage on database
# 	N.B.: if omitted, storing does not occur !
#   "<name_database> database name for game to storage

# "import_pdn" : PDN name from which to view the game
#   N.B.: valid only in 'view' mode !
#   "<name_pdn> PDN name for import/view

# "pk_game" : game identifier to view
#   N.B.: valid only in 'view' mode !
#   "<pk_game> game identifier in the chosen database (primary key=datetime)
#   N.B.: se PDN il time determina il numero della partita con stessa data !


# N.B.: TODO UL type option (with archive /dataset) !
#   N.B.: valid only in 'data' mode !
