[Configuration]

# "graphics" : graphical interface module
#   "pygame" with loop frame ideal for animated graphics 2D
#   "tkinter" with event loop ideal for static widget graphics 2D(GUI)
#   "pyOpenGL" with loop frame, uses OpenGL API for 3D graphics
#   "webapp" future extensions
#   "console" no graphics, only command line
graphics = pygame

# "mode" : type of execution mode
#   "play" checkers game between player 1 and player 2
#   "view" view checkers game from archive
#   "scan" like view mode but without graphics refresh
#   "data" Unsupervised Learning (UL) data extraction
# mode = play
mode = view
# mode = scan

# "player1_name" : identification player 1
#   "<name_player> name player for storage data
player1_name = name1 surname1

# "player1_engine" : type of decision engine for player 1
#   Hint: valid only in 'play' mode !
#   "player" mouse or keyboard moves
#   "classic" MiniMax + Alpha-Beta Pruning
#   "SL" Supervised Learning
#   "RL" Reinforcement Learning
player1_engine = player

# "player2_name" : identification player 2
#   "<name_player> name player for storage data
player2_name = name2 surname2

# "player2_engine" : type of decision engine for player 2
#   Hint: valid only in 'play' mode !
#   "player" mouse or keyboard moves
#   "classic" MiniMax + Alpha-Beta Pruning
#   "supervised" Supervised Learning (SL)
#   "reinforcement" Reinforcement Learning (RL)
player2_engine = player

# "parity_move" : Maximum number of moves without capturing any pieces and
# without moving any mans (counted by both players)
# parity_move = 20

# "restore" : restore checkerboards state from archive /restores
#   Hint: delete option if normal game start !
#   "<name_checkerboard> checkerboard state name
# restore = state_reset.json
# restore = state_test01.json
# restore = state_test02.json

# "history_database" : activation of historical game storage on database
# 	Hint: if omitted, storing does not occur !
#   "<name_database> database name for game to storage

# "pk_game" : game identifier to view
#   Hint: valid only in 'view' mode !
#   "<pk_game> game identifier in the chosen database (primary key=datetime)

# "import_pdn" : PDN filename from which to view the game
#   Hint: valid only in 'view' mode !
#   "<name_pdn> PDN filename for import/view
import_pdn = CI2004.pdn

# "pdn_game" : game identifier in pdn (first game unless specified)
#   Hint: Valid only with' import_pdn' !
#   String containing order number of the match where the 'view' from PDN begins
# pdn_game = 120

# "timeout_selected" : timeout selected in msec for moves steps in view mode. 
# Setting it to zero will make the timeout infinite; to continue, a keyboard (space) or 
# mouse (left-click) event is required
#   Hint: valid only in 'view' mode !
timeout_selected = 0

# "timeout_destinated" : timeout destinated in msec for moves steps in view mode. 
# Setting it to zero will make the timeout infinite; to continue, a keyboard (space) or 
# mouse (left-click) event is required
#   Hint: valid only in 'view' mode !
timeout_destinated = 2000

# "timeout_validated" : timeout validated in msec for moves steps in view mode. 
# Setting it to zero will make the timeout infinite; to continue, a keyboard (space) or 
# mouse (left-click) event is required
#   Hint: valid only in 'view' mode !
timeout_validated = 2000

# "seed" : use for randomization with testable determinism
# seed = 23

# Hint: TODO UL type option (with archive /dataset) !
#   Hint: valid only in 'data' mode !
